### ISSUE TITLE
[PE-D][Tester A] delete-p does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T14-2/tp#105]
Problem: delete-p command does not work
State: There are many entries with the name `John Doe` but with different phone number
Steps: When command shown in screenshot is executed, no error prompt is given. The given person with phone number does not exist in screenshot

![Screenshot 2024-04-05 162612.png](https://raw.githubusercontent.com/Rikko1204/ped/main/files/c0129caa-3686-48c0-8dc8-a1cbded711be.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Rikko1204/ped#1

**Comment by jeong-jaeho** [comment]
Resolved the bug.
