### ISSUE TITLE
[PE-D][Tester C] Adding a visit to a patient puts them at the bottom of the list

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T14-2/tp#107]
It may be subjective but I feel that adding a visit to a patient should put the patient on the top of the list and not the bottom. This is to help confirm that the patient was indeed added.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: ivan24004/ped#3

**Comment by Vision-2000** [comment]
Functionality change required, check that behaviour is stated in UG.
