### ISSUE TITLE
[PE-D][Tester A] deletev does not work as intended

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T14-2/tp#137]
Problem: When `deletev` command is given for the person in screenshot 1, the visit is not deleted, and the details of the visit is changed whenever the same command is executed as shown in screenshot 2.

Steps: Execute the command shown repeatedly with a valid person's details

![Screenshot 2024-04-05 172900.png](https://raw.githubusercontent.com/Rikko1204/ped/main/files/5a65250c-65e0-419c-b1d7-0b1a46761546.png)

![Screenshot 2024-04-05 173052.png](https://raw.githubusercontent.com/Rikko1204/ped/main/files/867a4a77-1979-4fd2-a040-89181c605eac.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Rikko1204/ped#8

**Comment by Vision-2000** [comment]
Attempted to replicate bug but failed, will keep in view but likely a user error.

**Comment by Vision-2000** [comment]
Closing as the bug cannot be verified.
